name: jokes_repository
description: A repository that handles jokes requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  mocktail: ^1.0.4

dev_dependencies:
  test: ^1.28.0
  very_good_analysis: ^10.0.0
